### ISSUE TITLE
Make the "Create New Enrollment" Button on the Welcome Page Testable

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#248] opened 2017-07-06 20:26 UTC
# Problem
For Selenium tests, elements on the page should be easily selectable via JQuery paths. The "Create New Enrollment" button on the welcome page doesn't have an id and shares the same path with the "Get Profiles" Button.

# Solution
Give both buttons unique IDs and update the Selenium tests to use them

**Comment by jasonaowen** [comment] 2017-09-18 22:24
Duplicate of #333.

**Closed by jasonaowen** 2017-09-18 22:24 UTC
Labels: quick-fix
