### ISSUE TITLE
Podiatrist can't submit enrollment

### ISSUE THREAD

**Issue by jasonaowen** [OpenTechStrategies/psm#299] opened 2017-07-26 13:45 UTC
Our sample data appears to have no issuing board(s) for the Podiatrist provider type, so Podiatrists cannot complete the enrollment process.

See also #293.

**Comment by cecilia-donnelly** [comment] 2017-07-28 17:06
I think this is a duplicate of #233.  Feel free to reopen if I'm wrong.

**Closed by cecilia-donnelly** 2017-07-28 17:06 UTC
Labels: bug

**Comment by jasonaowen** [comment] 2017-07-28 18:28
Whoops, so it is! Sorry about that.

**Comment by kfogel** [comment] 2018-03-03 03:11
Did this mean to say "seed data" where it says "sample data"?  (Same question asked in several other issues, all around this time, btw.)

In this issue, it doesn't really matter, since it was closed as a dup anyway.  But I thought I'd be complete and make the comment here too, in case anyone ever reads this issue.
