### ISSUE TITLE
PostgreSQL jar hash error

### ISSUE THREAD

**Issue by cecilia-donnelly** [OpenTechStrategies/psm#31] opened 2017-05-18 21:25 UTC
I've deployed `postgresql-42.1.1.jar` to my local Wildfly server.  Each time I start that server, I get the error: 

```
WFLYSRV0137: No deployment content with hash <hash> is available in the deployment content repository for deployment 'postgresql-42.1.1.jar'
```

I can delete the `postgresql-42.1.1.jar` deployment from `standalone-full.xml` and redeploy it and all works correctly.  @jasonaowen has also seen this error when he has multiple local deployments.

Leaving an issue here for our records in case this continues to be a problem.  It's not a blocker, just a minor annoyance.

**Comment by jasonaowen** [comment] 2017-07-31 15:42
This problem seems to be with how we were initially using WildFly, and has stopped coming up as we learned how to use it effectively. Have you seen this recently, @cecilia-donnelly ? If not, can we close this?

**Comment by jasonaowen** [comment] 2017-09-29 16:39
We haven't seen this recently, and haven't been able to reproduce it. If we encounter this problem again, we can reopen this issue.

**Closed by jasonaowen** 2017-09-29 16:39 UTC
Labels: bug, tech-debt
