### ISSUE TITLE
Add checkstyle plugin to Gradle Build

### ISSUE THREAD

**Issue by BenGalewsky** [OpenTechStrategies/psm#188] opened 2017-06-20 13:55 UTC
# Problem
We need to enforce coding standards and best practice on all assets in this project, but there is a significant base of code already in the repo.

# Task
- [ ] Add checkstyle plugin to the gradle build
- [ ] Agree a set of checks to apply
- [ ] Create a filter to allow checkstyle to pass all of the existing code, but require developers to 
include checks in any file that is touched during the project

**Comment by jasonaowen** [comment] 2017-09-29 16:34
Duplicate of #456

**Closed by jasonaowen** 2017-09-29 16:34 UTC
